* \section{Persistency for Groupware Data}
Relational Databases vs. NoSQL databases vs. plain files

Relational databases are not practical for contacts, events or todos. Common patterns in systems that use relational DBs for that purpose:
\begin{itemize}
\item artificial limits of entries, e.g. only 3 email addresses per contact, because there are only three columns email1, email2 and email3.
\item Fields for custom data like custom1 to customX
\item EAV pattern: tables like: id, foreign\_id, type, value
\end{itemize}
\section{Synchronizing a large collection}

How to efficiently synchronize a large collection of contacts with the server without checking each contact for changes?

Portable Contacts has a filter ``updatedSince''.

How is synchronization done in CardDAV?

``Feed Paging for Efficient Feed Synchronization'' thread at ATOM-Syntax \url{http://www.imc.org/atom-syntax/mail-archive/msg20060.html}

HTTP Delata encoding with Feed: \citeurl{http://www.wyman.us/main/2004/09/using_rfc3229_w.html}{2012-1-6}, implementations: \citeurl{http://www.wyman.us/main/2004/09/implementations.html}{2011-1-6}

``There's also an advanced technique involving etags which keeps track of when
each etag was issued and if an old etag is sent with the request then
everything since then is sent back in the response. Someone will chime in
with the reference.'' Eric Scheid, \citeurl{http://www.imc.org/atom-syntax/mail-archive/msg19832.html}{2012-1-6}

Microsoft specification FeedSync (formerly Simple Sharing Extension) \url{http://feedsyncsamples.codeplex.com},
 comment \url{http://notes.kateva.org/2008/01/microsoft-feedsync-what-heck-is-it-and.html}
\url{http://web.archive.org/web/20081114142152/http://www.snellspace.com/wp/?p=818}

* \section{Media Types}

\begin{table}
  \begin{tabular}{l c c c c c}
    type of data & XML  & JSON                      & semantic          & microformat & comment \\
    Calendar     & xCal & Google calendar API       & \url{http://www.w3.org/TR/rdfcal} & hCalendar & other: iCalendar  \\
    Contact      & xCard & portable contacts, jCard & friend of a friend & hCard & other: vCard \\
    Resume       & HR XML &                          & Description of a Career & hResume & \\    
  \end{tabular}
  \caption{data in different formats}
  \label{tab:data-formats}
\end{table}


% Open-Xchange provides an (unrestful) HTTP/JSON API which is used by its
% javascript
% frontend.\footnote{\citeurl{http://oxpedia.org/index.php?title=HTTP_API}{2011-19-12}}
% The comprehensive documentation does not indicate whether the data structures
% for tasks, appointments, reminders and contacts were inspired by any
% standards. In any case the API documentation is a good example of the need for
% standard mime types in JSON format. The use case for this API also shows
% similarities to the use of OpenSocial for intranet frontends.
\subsection{Media Type conversion}

RFC 5023  "Collections are represented as Atom Feeds"

Is conneg (content negotiation) useful?
No: Norman Walsh, 2003, it can lead to hard to debug bugs\citeurl{http://norman.walsh.name/2003/07/02/conneg}{2011-1-9},
    Joe Gregorio, 2003,I can't communicate the mime type to request to a third service if I can only give an URI\citeurl{http://bitworking.org/news/WebServicesAndContentNegotiation}{2011-1-9}
Yes: Jerome Louvel, 2006, I could additionally provide URIs that override the accept headers with query parameters like ?format=json.\citeurl{http://blog.noelios.com/2006/11/15/reconsidering-content-negotiation/}{2011-1-9}
    

\begin{quote}
  No single data representation is ideal for every client. This protocol defines representations for each resource in three widely supported formats, JSON [RFC4627], XML, and Atom [RFC4287] / AtomPub [RFC5023], using a set of generic mapping rules. The mapping rules allow a server to write to a single interface rather than implementing the protocol three times.
\end{quote}\cite[Core API Server]{OSSpec2.0.1}

% microformats to json converter \url{http://microformatique.com/optimus/}


In 2007, a project called microjson wanted to standardize json representations of microformat data structures.\footnote{\citeurl{http://notizblog.org/2007/09/16/microjson-microformats-in-json/}{2011-12-19}} 

The project identified the need for a json schema:\footnote{\citeurl{http://web.archive.org/web/20080524003749/http://microjson.org/wiki/Schemas}{2022-12-19}}
\begin{quote}
  If there are standard microJSON formats for transfer of certain datasets, there will be a need to validate that data to ensure that it is infact valid format. To validate a format you need something that details the structure, data content types and required data. Sounds like we'll be needing a schema for each microJSON format. 
\end{quote}


jCard example from microjson.org\footnote{\citeurl{http://web.archive.org/web/20080517003233/http://microjson.org/wiki/JCard}{2011-12-19}}
\begin{lstlisting}
{
"vcard":{
  "name":{
    "given":"John",
    "additional":"Paul",
    "family":"Smith"
  },
  "org":"Company Corp",
  "email":"john@companycorp.com",
  "address":{
    "street":"50 Main Street",
    "locality":"Cityville",
    "region":"Stateshire",
    "postalCode":"1234abc",
    "country":"Someplace"
  },
  "tel":"111-222-333",
  "aim":"johnsmith",
  "yim":"smithjohn"
}
\end{lstlisting}

\subsection{Example: vCard}

\begin{lstlisting}
   <?xml version="1.0" encoding="UTF-8"?>
   <vcards xmlns="urn:ietf:params:xml:ns:vcard-4.0">
     <vcard>
       <fn><text>Simon Perreault</text></fn>
       <n>
         <surname>Perreault</surname>
         <given>Simon</given>
         <additional/>
         <prefix/>
         <suffix>ing. jr</suffix>
         <suffix>M.Sc.</suffix>
       </n>
       <bday><date>--0203</date></bday>
       <anniversary>
         <date-time>20090808T1430-0500</date-time>
       </anniversary>
       <gender><sex>M</sex></gender>
       <lang>
         <parameters><pref><integer>1</integer></pref></parameters>
         <language-tag>fr</language-tag>
       </lang>
       <lang>
         <parameters><pref><integer>2</integer></pref></parameters>
         <language-tag>en</language-tag>
       </lang>
       <org>
         <parameters><type><text>work</text></type></parameters>
         <text>Viagenie</text>
       </org>
       <adr>
         <parameters>
           <type><text>work</text></type>
           <label><text>Simon Perreault
   2875 boul. Laurier, suite D2-630
   Quebec, QC, Canada
   G1V 2M2</text></label>
         </parameters>
         <pobox/>
         <ext/>
         <street>2875 boul. Laurier, suite D2-630</street>
         <locality>Quebec</locality>
         <region>QC</region>
         <code>G1V 2M2</code>
         <country>Canada</country>
       </adr>
       <tel>
         <parameters>
           <type>
             <text>work</text>
             <text>voice</text>
           </type>
         </parameters>
         <uri>tel:+1-418-656-9254;ext=102</uri>
       </tel>
       <tel>
         <parameters>
           <type>
             <text>work</text>
             <text>text</text>
             <text>voice</text>
             <text>cell</text>
             <text>video</text>
           </type>
         </parameters>
         <uri>tel:+1-418-262-6501</uri>
       </tel>
       <email>
         <parameters><type><text>work</text></type></parameters>
         <text>simon.perreault@viagenie.ca</text>
       </email>
       <geo>
         <parameters><type><text>work</text></type></parameters>
         <uri>geo:46.766336,-71.28955</uri>
       </geo>
       <key>
         <parameters><type><text>work</text></type></parameters>
         <uri>http://www.viagenie.ca/simon.perreault/simon.asc</uri>
       </key>
       <tz><text>America/Montreal</text></tz>
       <url>
         <parameters><type><text>home</text></type></parameters>
         <uri>http://nomis80.org</uri>
       </url>
     </vcard>
   </vcards>
\end{lstlisting}

\begin{lstlisting}
   <?xml version="1.0" encoding="UTF-8"?>
   <vcards xmlns="urn:ietf:params:xml:ns:vcard-4.0">
     <vcard>
       <fn><text>Simon Perreault</text></fn>
       <n>
         <surname>Perreault</surname>
         <given>Simon</given>
         <suffix>ing. jr</suffix>
         <suffix>M.Sc.</suffix>
       </n>
       <bday day="02" month="03" />
       <anniversary format="date-time">20090808T1430-0500</anniversary>
       <gender>M</gender>
       <lang pref="1">fr</lang>
       <lang pref="2">en</lang>
       <org type="work">Viagenie</org>
       <adr type="work">
         <label>Simon Perreault
   2875 boul. Laurier, suite D2-630
   Quebec, QC, Canada
   G1V 2M2</label>
         <street>2875 boul. Laurier, suite D2-630</street>
         <locality>Quebec</locality>
         <region>QC</region>
         <code>G1V 2M2</code>
         <country>Canada</country>
       </adr>
       <tel>
         <type>work</type>
         <type>voice</type>
         <uri>tel:+1-418-656-9254;ext=102</uri>
       </tel>
       <tel>
         <type>work</type>
         <type>text</type>
         <type>voice</type>
         <type>cell</type>
         <type>video</type>
         <uri>tel:+1-418-262-6501</uri>
       </tel>
       <email type="work">simon.perreault@viagenie.ca</email>
       <geo type="work">
         <uri>geo:46.766336,-71.28955</uri>
       </geo>
       <key type="work">
         <uri>http://www.viagenie.ca/simon.perreault/simon.asc</uri>
       </key>
       <tz>America/Montreal</tz>
       <url type="home">
         <uri>http://nomis80.org</uri>
       </url>
     </vcard>
   </vcards>
\end{lstlisting}

\subsection{HFactor}
Mike Amundsen defines a method to asses media types that he calls
``HFactor''.\footnote{\citeurl{http://amundsen.com/hypermedia/}{2011-12-21}} The
HFactor distinguishes different types of support for links and indicates which
of those are provided by a reviewed media type.

Amundsen did reviews of a couple of media types. Unfortunately these do not
include \texttt{vcard+xml} or \texttt{calendar+xml}. I'll try to identify the
HFactors of both here.

The different types of link support have two letter acronyms and fall in two
categories: Link support values, with the first letter ``L'' and Control data
support, first letter ``C''.

\begin{itemize}
\item Link Support for
  \begin{itemize}
  \item \texttt{LE} embedded links (HTTP GET)
  \item \texttt{LO} out-bound navigational links (HTTP GET)
  \item \texttt{LT} templated queries (HTTP GET)
  \item \texttt{LN} non-idempotent updates (HTTP POST)
  \item \texttt{LI} idempotent updates (HTTP PUT, DELETE) 
  \end{itemize}
\item Control Data Support to
  \begin{itemize}
  \item \texttt{CR} modify control data for read requests (e.g. \texttt{HTTP Accept-*} headers)
  \item \texttt{CU} modify control data for update requests (e. g. \texttt{Content-*} headers)
  \item \texttt{CM} indicate the interface method for requests (e.g. HTTP GET,POST,PUT,DELETE methods)
  \item \texttt{CL} add semantic meaning to link elements using link relations (e.g. HTML rel attribute)
  \end{itemize}
\end{itemize}

ezPublish or Drupal implement the dynamic object model, see Dirk Riehle

* \subsection{Data Models of Media Types}

TODO:
\begin{itemize}
\item Ein generelles Daten Modell wäre hilfreich, um alle Medien Typen darauf zu projezieren und mit einer solchen Projektion dann innerhalb der Applikation zu arbeiten (TODO Schreier: warum muss dass Datenmodell total allgemeingültig sein, reicht es nicht vielleicht auch für eine Domäne?)
\item Ein allgemeines Datenmodell könnte auch eine Hilfe sein als Zwischenschritt für Conversions zwischen Medientypen
\item Es gibt kein allgemeines, sinnvolles Datenmodell für alle Medientypen
\item Trotzdem können bestimmte hilfreiche Generalisierungen vorgenommen werden
  \begin{itemize}
  \item Die meisten Resourcen haben bestimmte generische Metadaten die entweder im Medientyp kodiert werden können oder mit dem Medientyp zusammen persistiert werden müssen
  \item Diese Metadaten finden sich auch in atom:entry wieder und sind: Autor, Updated, Titel, Summary, etag, id, name, links
  \item Transitional Links vs Structural Links: \url{http://java.net/projects/jax-rs-spec/pages/Hypermedia}
  \item Different categories of data: CSV, binary/plain text, large binary (video), tree (XML/JSON) (Referenz?)
  \end{itemize}
\end{itemize}

* \section{Hypermedia in RESTful applications}

% Hat Kolab Hypermedia links in Kontakten, wie soll es sein mit xCard?

% http://restpatterns.org/Articles/The_Hypermedia_Scale

% http://linkednotbound.net/2010/12/01/web-linking/
% it is not sufficient for
% data to simply contain URIs for it to be “linked”. There must be a
% specification of the format that identifies those URIs as links, and either
% defines the link semantics or how they can be determined. The link might be
% part of a generic link construct like the Atom and HTML <link> elements,
% referencing a relation from the link relation registry that provides the link
% semantics. Alternatively, the link semantics might be defined in the data
% format, as was the case in the “next” property from our example.

% REST has four architectural constraints:
% separation of resource from representation,
% manipulation of resources by representations,
% self-descriptive messages, and
% hypermedia as the engine of application state.

% http://amundsen.com/hypermedia/hfactor/

% Hypermedia as the engine of application state
% http://www.infoq.com/articles/mark-baker-hypermedia

\begin{quotation}
  The model application is therefore an engine that moves from one state to the next by examining and choosing from among the alternative state transitions in the current set of representations.
\end{quotation}\cite[sec. 5.3, p.103]{Fielding2000}

** \subsection{Hypermedia in OpenSocial}

Webfinger, e.g. get a profile picture from an email address

Danger: One can trigger na http request by sending an email.

* \section{Selection of components}

Apache Shindig for Open Social, includes client tests

http://code.google.com/p/kolab-android/

https://evolvis.org/projects/kolab-ws/

http://packages.ubuntu.com/source/maverick/dovecot-metadata-plugin
https://launchpad.net/ubuntu/+source/dovecot-metadata-plugin/8-0ubuntu1

% Apache Felix, Jackrabbit, RESTeasy http://blog.tfd.co.uk/2011/11/25/minimalist/
% Scala Dispatch HTTP requests http://dispatch.databinder.net/Dispatch.html
% Scala JSON serialization https://github.com/debasishg/sjson
% ATOM http://abdera.apache.org/ http://www.ibm.com/developerworks/xml/library/x-atompp3/ http://www.ibm.com/developerworks/xml/library/x-tipatom4/index.html

% JSON: http://jackson.codehaus.org/ http://code.google.com/p/google-gson/
% http://microformats.org/wiki/org.microformats.hCard

% Universal ATOM client/server? http://code.google.com/p/dase/ (PHP/MySQL, Python client)
% https://github.com/arktekk/atom-client

% http://code.google.com/p/atombeat/ atombeat eXistDB, atompub, java, Uni Oxford, mostly written in XQuery, Spring based security
% http://atomserver.codehaus.org Adds non standard and not restful extensions (e.g. feed aggregation with special URLs) inspired by GData, expects a relational database
% more http://code.google.com/p/atomojo java atompub feed server on existDB 
% http://atomhopper.org 
% existDb has an own atompub impl http://exist-db.org/atompub.html


** \subsection{REST framework}
Jersey recommended by \cite{Kaiser2011} above Restfulie and RESTeasy because of maturity and flexibility.

% http://www.torsten-horn.de/techdocs/jee-rest.htm RESTful Web Services mit JAX-RS und Jersey

Jersey has a atompub-contact client/server example app.

Why not Jersey in the end?
\begin{itemize}
\item JAX-RS assumes, that Paths are defined on the classes that represent the resources.
  \begin{itemize}
  \item This couples the ``location'' of a resource to its implementation.
  \item This leads to copied code. Given an URL pattern like
    \verb:/{AUTHORITY}/{COLLECTION}/{ENTRY}:. In this case the resource classes
    for authority, collection and entry would each need to parse the authority
    section of the path.
  \item If paths are not defined on resource classes, it is not possible to make use of JAX-RS' capabilities of declarative hyperlink building (@REF annotation).
  \end{itemize}
\item The dispatch to a request handler method has in our case three orthogonal
  parameters: HTTP verb, Media type, path. It would be preferable to handle
  these parameters independent of each other. The only way to handle at least
  the path dispatch separately is with the help of sub resources. This still
  leaves HTTP verb and Media type to be handled together.

  The sub resource mechanism additionally suffers from the shortcoming that it does not allow to specify an empty path.\footnote{\citeurl{http://java.net/jira/browse/JERSEY-536}{2012-01-21}} This makes it impossible to return a sub resource and annotate a method that should handle the case that no additional path elements remain to be matched.

\item Debugging is hard. It's not trivial to find out, why Jersey did not select a request handler or provider as the developer intended.
\item Jersey's parameter injection can not be used together with a dependency injection framework like Guice or Spring.
\end{itemize}

Comments on Restlet:
\begin{itemize}
\item A couple of core classes of Restlet extend a class called Restlet whose
  purpose is only vaguely defined but the type inheritance does not correspond
  to an ``is-a'' relationship. This might indicate a questionable architecture
  of the framework.
\item Classes in Restlet are generally mutable. The Javadocs of several classes,
  e.g. org.restlet.Restlet and subclasses even come with a warning note but do
  not expose any information about the thread-safety of their methods:
  \begin{quote}
    Concurrency note: instances of this class or its subclasses can be invoked by several threads at the same time and therefore must be thread-safe. You should be especially careful when storing state in member variables. 
  \end{quote}
\item 
\end{itemize}

\subsection{VCard}

% http://sourceforge.net/projects/vcard4j is dead since 5
% years. http://sourceforge.net/projects/mime-dir-j forked and updated and is
% now also abandoned.
% http://sourceforge.net/projects/jpim/ dead since 2 years.
% active:
% http://code.google.com/p/android-vcard 
% http://sourceforge.net/projects/cardme/
% http://wiki.modularity.net.au/ical4j/index.php?title=VCard (easily extendable to XML, JSON)


ical4j 
best documented
best code
is used by 
most active
also supports icalendar
is immutable!!!

\section{Testing}
How to test the ReST/CardDAV interface?

% http://code.google.com/p/rest-client/
% http://bitworking.org/projects/apptestclient GUI based Atom Publishing Protocol Client
% 

% Jersey creates WADL documents for OPTION requests. http://wadl.java.net/ seems to provide clients

Portable Contacts test client at plaxo \url{http://www.plaxo.com/pdata/testClient}

\url{http://code.google.com/p/rest-assured/} \url{http://restfuse.com/}

* \section{Standards}
** \subsection{Contacts / Persons}

% http://schema.org/Person

% http://www.ibiblio.org/hhalpin/homepage/notes/vcardtable.html
\begin{description}[\breaklabel\setleftmargin{1ex}]

  \item[RFC 6450 vCard Format Specification]
    This document defines the vCard data format for representing and exchanging
    a variety of information about individuals and other entities (e.g.,
    formatted and structured name and delivery addresses, email address,
    multiple telephone numbers, photograph, logo, audio clips, etc.). This is
    the new version and obsoletes RFCs 2425, 2426, and 4770, and updates RFC
    2739.

  \item[RFC 6351 xCard: vCard XML Representation]
    This document defines the XML schema of the vCard data format. 

  % http://portablecontacts.net/draft-spec.html
  % http://docs.opensocial.org/display/OSD/Specs
  % http://docs.opensocial.org/display/OSD/Enterprise+OpenSocial+Extensions link to calendar!
  % Mozilla erwägt PoCo http://groups.google.com/group/mozilla.dev.webapi/browse_thread/thread/3bd36f73336ce783?pli=1
  % https://code.google.com/apis/contacts/docs/poco/1.0/developers_guide.html
  \item[Portable Contacts, OpenSocial] 
    Portable Contacts defines contact data structures and a ReST API. It has
    been integrated in the OpenSocial standard.

  % http://www.nuxeo.com/en/resource-center/Videos/Nuxeo-World-2011/Leveraging-Open-Social-within-the-Nuxeo-Platform
  % http://wiki.magnolia-cms.com/display/WIKI/Magnolia+OpenSocial+Container
  % http://www.zdnet.com/blog/hinchcliffe/opensocial-20-will-key-new-additions-make-it-a-prime-time-player-in-social-apps/1603
  % http://www.cmswire.com/cms/social-business/open-standards-the-future-of-opensocial-20-013335.php
  % http://docs.opensocial.org/display/OSD/List+of+OpenSocial+Containers
  % http://www.informationweek.com/thebrainyard/news/industry_analysis/232200026
  % http://www.atlassian.com/opensocial/

  \item[Nepomuk Semantic Desktop Contact Ontology]

  % http://xmlns.com/foaf/spec/
  \item[Friend of a friend (FOAF)] 
    FOAF is a 

  % http://microformats.org/wiki/hcard
  \item[hCard]

  % http://microformats.org/wiki/jcard
  \item[jCard]

\end{description}

** \subsection{Calendaring}
%\subparagraph{IETF (RFC)}
\begin{description}[\breaklabel\setleftmargin{1ex}]

  \item[RFC 5545 Internet Calendaring and Scheduling Core Object Specification]

    iCalendar is the core data schema for calendaring information. This is the
    new version and obsoletes RFC2445

  \item[RFC 6321 xCal: The XML format for iCalendar]

    This specification defines a format for representing iCalendar data in
    XML. More specifically, is to define an XML format that allows iCalendar
    data to be converted to XML, and then back to iCalendar, without losing any
    semantic meaning in the data. Anyone creating XML calendar data according to
    this specification will know that their data can be converted to a valid
    iCalendar representation as well.

  \item[CalWS RESTful Web Services Protocol for Calendaring]

    This document, developed by the XML Technical Committee, specifies a RESTful
    web services Protocol for calendaring operations. This protocol has been
    contributed to OASIS WS-CALENDAR as a component of the WS-CALENDAR
    Specification under development by OASIS.

  % https://code.google.com/apis/calendar/v3
  \item[Google Calendar API V3]

    While not being a standard, the Google Calendar API is RESTful and will
    surely be implemented by many client applications. It's remarkable that the
    API supports partial GETs returning only specified fields and the HTTP PATCH
    verb to update only specified fields.

  % http://open-services.net/specifications/
  \item[Open Services for Lifecycle Collaboration (OSLC)]

    uses FOAF person \url{http://open-services.net/bin/view/Main/OSLCCoreSpecAppendixA?sortcol=table;up=#foaf_Person_Resource}

    provides change management, some overlapping to iCal TODOs \url{http://open-services.net/bin/view/Main/CmSpecificationV2}

    reference implementation: \url{http://eclipse.org/lyo}

\end{description}

** \subsection{Scheduling}

\begin{description}[\breaklabel\setleftmargin{1ex}]
  \item[RFC 5546 iCalendar Transport-Independent Interoperability Protocol (iTIP)] 

    Scheduling Events, BusyTime, To-dos and Journal Entries; Specifies
    the mechanisms for calendaring event interchange between calendar
    servers. This is the new version and obsoletes RFC2446

  \item[RFC 6047 iCalendar Message-Based Interoperability Protocol (iMIP)]

    Specifies how to exchange calendaring data via e-mail. This is the new
    version and obsoletes RFC2447.

\end{description}

** \subsection{Relations and Links}
% http://code.google.com/apis/socialgraph/
\begin{description}[\breaklabel\setleftmargin{1ex}]

  % http://gmpg.org/xfn/
  \item[Xhtml Friends Network (XFN)] 

    One of the relations returned by Google's webfinger.

  % https://datatracker.ietf.org/doc/draft-jones-appsawg-webfinger/
  \item[Webfinger]
    Webfinger in Firefox Contacts Add-On \url{http://mozillalabs.com/blog/2010/03/contacts-in-the-browser-0-2-released/}

  \item[RFC 6415 Web Host Metadata]

  % http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html
  % http://en.wikipedia.org/wiki/XRDS
  % http://code.google.com/p/webfinger/wiki/CommonLinkRelations
  % http://hueniverse.com/category/discovery/
  \item[Extensible Resource Descriptor (XRD)] 

\end{description}

** \subsection{out of scope}
\begin{description}[\breaklabel\setleftmargin{1ex}]

  % LDIF for person info

  % http://www.hr-xml.org
  % http://de.wikipedia.org/wiki/HR-XML  
  \item[HR XML]

    The HR-XML Consortium is the only independent, non-profit, volunteer-led
    organization dedicated to the development and promotion of a standard suite
    of XML specifications to enable e-business and the automation of human
    resources-related data exchanges.

  % http://www.openmobilealliance.org/Technical/release_program/cab_v1_0.aspx
  \item[OMA Converged Address Book V1.0]

    Standard by the Open Mobile Alliance defining data structures and
    synchronization of contact data. It references vCard.
  
  % http://en.wikipedia.org/wiki/Open_Collaboration_Services
  \item[Open Collaboration Services]

    Also contains data structures for persons and events but does not reuse any
    known standard. See this thread:
    \url{http://lists.freedesktop.org/archives/ocs/2011-December/000136.html}

  % http://www.w3.org/TR/contacts-api
  \item[W3C Contacts API]

    A standard on how address books cold be accessed on devices or from
    JavaScript inside a Web Browser. The standard references vCard, OMA
    Converged Address Book and Portable Contacts.

  % http://www.w3.org/TR/vcard-rdf/
  \item[W3C vCard ontology]

  % http://www.w3.org/2000/10/swap/pim/contact
  \item[W3C PIM ontology]

\end{description}

* \section{People, Groups and Organizations}
% http://lists.w3.org/Archives/Public/public-device-apis/ - Contacts API
% 
% https://www.ietf.org/mailman/listinfo/calsify
% https://www.ietf.org/mailman/listinfo/ischedule - only 8 mails since 2009
% https://www.ietf.org/mailman/listinfo/httpmail only 3 mails since 2009
% https://www.ietf.org/mailman/listinfo/vcarddav
% https://www.ietf.org/mailman/listinfo/caldav
% https://www.ietf.org/mailman/listinfo/imap5

%http://groups.google.com/group/portablecontacts

%http://tech.groups.yahoo.com/group/rest-discuss

\paragraph{People}
\begin{description}[\breaklabel\setleftmargin{1ex}]

  \item[Eran Hammer-Lahav]
      \url{http://hueniverse.com}
      Yahoo!, OAuth

  \item[Eliot Lear <lear@cisco.com>]
      IETF Calsify WG chair

  \item[James Snell]
    \url{http://chmod777self.blogspot.com/}

    Apache Abdera committer, OpenSocial, IBM

  \item[Joseph Smarr]

    former Plaxo now Google
    presentation about portable contacts at vcarddav wg http://tools.ietf.org/agenda/74/slides/vcarddav-2.pdf
    http://josephsmarr.com
    http://anyasq.com/79-im-a-technical-lead-on-the-google+-team

  \item[Julian Reschke <julian.reschke@gmx.de>]
% Julian Reschke, WebDAV Experte, RFC 5995, greenbytes GmbH,Hafenweg 16, 48155 Münster , Germany

  \item[Lisa Dusseault]
      
    Lisa Dusseault is a development manager and standards architect at the Open
    Source Applications Foundation, where she's involved in the Chandler, Cosmo
    and Scooby projects. Previously, Lisa came from Xythos, an Internet startup
    where she was development manager for four years. She has also been an IETF
    contributor on various Internet applications protocols for eight years now,
    and continues to do this kind of work at OSAF. She co-chairs the IETF IMAP
    extensions and CALSIFY (Calendaring and Scheduling Standards Simplification)
    Working Groups. She is also the author of a book on WebDAV and co-author of
    CalDAV, an open and interoperable protocol for calendar access and sharing.

  \item[Mark Nottingham]
%  http://www.mnot.net/personal/

  \item[Mike Amundsen <mamund@yahoo.com>]
    \url{http://amundsen.com}

  \item[Mike Conley]

    \url{http://mikeconley.ca/blog/}
    % Email: mike.d.conley@gmail.com
    % Twitter: http://www.twitter.com/mike_conley
    % IRC: You can usually find me on Freenode as m_conley
    working on a new address book for Thunderbird: \url{https://wiki.mozilla.org/Thunderbird/tb-planning}

  \item[Peter Saint-Andre <stpeter@stpeter.im>]

    IETF Calsify WG area director

% http://notizblog.org/2011/11/17/the-long-term-failure-of-openweb/
\end{description}

* \section{Implementations}

% http://wiki.portablecontacts.net/w/page/17776143/Software%20and%20Services%20using%20Portable%20Contacts
% http://docs.opensocial.org/display/OSD/List+of+OpenSocial+Containers

% http://en.wikipedia.org/wiki/List_of_applications_with_iCalendar_support
% http://syncevolution.org/
% http://www.janrain.com/solutions/supported-networks
% http://code.google.com/p/caldav4j/
% http://www.webdav.org/projects/
% http://en.wikipedia.org/wiki/CardDAV
% webdav server http://milton.ettrema.com
% http://jackrabbit.apache.org/jackrabbit-webdav-library.html
% http://davmail.sourceforge.net/ Exchange GateWay using Jackrabbit
% http://en.wikipedia.org/wiki/List_of_applications_with_iCalendar_support
% Open Core: http://en.wikipedia.org/wiki/Open_core
% http://en.wikipedia.org/wiki/Groupware

** \subsection{Servers}
\begin{description}[\breaklabel\setleftmargin{1ex}]

  \item[Bedeworks]
    Java

  % http://en.wikipedia.org/wiki/Cyn.in
  \item[Cyn.in]
    Python, Open Core

  % http://www.davical.org/
  \item[DAViCal] 

    PHP, SQL storage, CalDAV, CardDav

  \item[eGroupWare]

  % http://en.wikipedia.org/wiki/EXo_Platform
  \item[eXo Platform]
    Open Core, Java, AGPL, participates in OpenSocial?

  % http://en.wikipedia.org/wiki/Group-Office
  \item[Group-Office]
    PHP, AGPL

  \item[Horde]

  % obm.org http://en.wikipedia.org/wiki/OBM_Groupware
  \item[OBM Groupware]
    PHP, GPL

  \item[Open-Xchange]
    Java, 
    In 2006 a Debian packaging attempt was canceled because upstream decided not to publish security updates for the open source version anymore.\footnote{\citeurl{http://web.archive.org/web/20100510133805/http://seraphyn.deveth.org/archives/10-Keine-Zukunft-in-der-freien-Version-von-Open-Exchange-auf-Debian.html}{2011-12-19}}

  % http://owncloud.org
  \item[owncloud]

    ownCloud supports syncing of calendar and contacts information via the
    CalDAV and CardDAV protocols.

  % http://en.wikipedia.org/wiki/Scalix
  \item[Scalix]
    Open Core
    Scalix Public License (SPL) based on MPL, requires to show the Scalix Logo

  % http://en.wikipedia.org/wiki/Simple_Groupware
  \item[Simple Groupware]
    PHP, GPL, SQL

  % http://en.wikipedia.org/wiki/SOGo
  \item[SOGo]
    CalDAV and CardDAV, written in Objective-C

  % http://en.wikipedia.org/wiki/Tiki_Wiki_CMS_Groupware
  \item[Tiki Wiki]
    PHP, SQL
    Contacts \url{http://doc.tiki.org/Contacts}, Calendar \url{http://doc.tiki.org/Calendar}
    iCal export
    apparently no CardDAV/CalDAV
    many many features!

  % http://en.wikipedia.org/wiki/Tine_2.0
  \item[Tine 2.0]
    Tine is not eGroupWare

  % http://en.wikipedia.org/wiki/Zarafa_%28software%29
  \item[Zarafa]
     PHP, MySQL
     IIRC it uses an Entity-Attribute-Value pattern to store its data in the relational db.

  % http://en.wikipedia.org/wiki/Zimbra
  \item[Zimbra]
    Open Core, Own license (Zimbra Public License),
    RFP since 2008 open: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=498316
    
\end{description}

** \subsection{Clients}

\begin{description}[\breaklabel\setleftmargin{1ex}]

  % http://en.wikipedia.org/wiki/Spicebird
  \item[Spicebird]
    built on top of Thunderbird with Calendar

  \item[Thunderbird]

    CardDAV via SoCO connector \url{http://www.sogo.nu/fr/downloads/frontends.html}

  \item[WebiCal]
   % http://code.google.com/p/webical/
     Java, YUI, Web frontend for a CalDAV server, uses iCal4J

  \item[Evolution, Evolution Data Server]
  \item[KDE Kontact, Akonadi]

  \item[more CardDAV] \url{http://wiki.davical.org/w/CardDAV/Clients} \url{http://en.wikipedia.org/wiki/CardDAV#Implementations}
  \item[more CalDAV]  \url{http://wiki.davical.org/w/CalDAV_Clients} \url{http://en.wikipedia.org/wiki/CalDAV#Implementations}

\end{description}


\subsection{Web Services}
% Google Calendar http://code.google.com/apis/calendar/caldav/

** \subsection{Others}

* \section{Links}

\begin{itemize}
\item \url{http://thesocialweb.tv}
\item \url{http://www.vogella.de/articles/REST/article.html} REST with Java (JAX-RS) using Jersey - Tutorial
\item \url{https://addons.mozilla.org/de/firefox/addon/restclient/}
\item \url{http://dataportability.org/} still active?
\item \url{http://tech.groups.yahoo.com/group/rest-discuss/messages/17242?threaded=1&m=e&var=1&tidx=1} REST and Semantic
\item \url{http://stackoverflow.com/questions/2669926/practical-advice-on-using-jersey-and-guice-for-restful-service}
\item \url{http://macstrac.blogspot.com/2009/01/jax-rs-as-one-web-framework-to-rule.html}
\item \href{http://keithp.com/blogs/calypso/}{Calypso — CalDAV/CardDAV/WebDAV for Android and Evolution}
\item \url{http://www.xfront.com/files/articles-1.html}
\item \url{http://buzzword.org.uk/swignition/uf}
\item \url{http://json-schema.org/}
\item \href{http://www.rddl.org/}{Resource Directory Description Language (RDDL)}
\item \url{http://blogs.oracle.com/sandoz/entry/jersey_and_abdera_with_a}  \url{http://weblogs.java.net/blog/mhadley/archive/2008/02/integrating_jer_2.html}
% http://exist.sourceforge.net/
% http://wiki.davical.org/w/CardDAV/Configuration/Well-known_URLs
% https://github.com/karl/monket-google-calendar A simplified UI for Google Calendar.
% Nuxeo switches from Python to Java: http://www.infoq.com/articles/nuxeo_python_to_java http://www.infoq.com/news/nuxeo-zope-java-migration
% JAXB Tutorial http://docs.oracle.com/cd/E17802_01/webservices/webservices/docs/1.6/tutorial/doc/JAXBWorks2.html
% XML Schema http://www.javaworld.com/javaworld/jw-08-2005/jw-0808-xml.html?page=2
% https://github.com/jaliss/securesocial provides OAuth, OAuth2 and OpenID authentication for Play Framework
% Oauth http://code.google.com/intl/de/apis/accounts/docs/OAuth2.html
% Permissions compared. IMAP, WEBDAV, ... http://chandlerproject.org/bin/view/Journal/LisaDusseault20040409
% Blog on calendar interop http://calendarswamp.blogspot.com

\end{itemize}

IANA link relations registry \url{http://www.iana.org/assignments/link-relations/link-relations.xml}

** linked data, microformats
 - http://www.w3.org/DesignIssues/LinkedData
 - http://manu.sporny.org/
 - http://dannyayers.com/2012/02/11/RDF-Hypermedia-is-Art
 - 

** \subsection{ATOM}
ATOM landscape overview \url{http://dret.typepad.com/dretblog/atom-landscape.html}
WebDAV vs. ATOM:
\url{http://intertwingly.net/wiki/pie/WebDav}
\url{http://intertwingly.net/wiki/pie/WebDavVsAtom}
google webdav atom
Why didn't ATOM succeed (more)? \citeurl{http://bitworking.org/news/425/atompub-is-a-failure}{2012-01-06}
% http://swordapp.org/

** \subsection{XML and JSON}

\begin{itemize}
\item \url{http://blog.jclark.com/}
\item \url{http://code.google.com/p/jaql/wiki/Builtin_functions#xml}
\item \url{http://www.webmasterworld.com/xml/3603303.htm}
\item \url{http://www.xml.com/pub/a/2006/05/31/converting-between-xml-and-json.html?page=3}
\item \url{http://goessner.net/download/prj/jsonxml/}
\item \url{http://www.w3.org/2011/10/integration-workshop/agenda.html}
\item \url{http://jsonml.org/}
\end{itemize}

** \subsection{Apache Shindig}
RPC vs. REST API for Shindig/OpenSocial: \url{http://groups.google.com/group/opensocial-and-gadgets-spec/browse_thread/thread/a4ddf7cd09f90237/5cfa1658e1c1d698?lnk=gst&q=rest#5cfa1658e1c1d698}, \url{http://groups.google.com/group/opensocial-and-gadgets-spec/browse_thread/thread/d1a5627fb6e686ce/d27d47dee92a87b2} One argument was support for batching. A restful batching proposal didn't get consensus: \url{https://docs.google.com/View?docid=dc43mmng_23fdbpp7hd&pli=1}

Flow of REST requests in Shindig \url{https://sites.google.com/site/opensocialarticles/Home/shindig-rest-java}

Google+ is likely to become OpenSocial enabled: \url{http://groups.google.com/group/opensocial-and-gadgets-spec/browse_thread/thread/1187241df6759a9a}

Shindig issues to implement OpenSocial 2.0 \url{https://docs.google.com/spreadsheet/ccc?key=0AihdZBncP3KzdGN3dVl3MFpIUlk2TXIyR3hfUDhHZUE&hl=en_US#gid=0}

How Shindig supports extensions: \url{https://cwiki.apache.org/confluence/display/SHINDIG/Arbitrary+Extensions+to+Apache+Shindig%27s+Data+Model}

Videos about some 2.0 OS features \url{http://groups.google.com/group/opensocial-and-gadgets-spec/browse_thread/thread/7b911edfb1bb3b4d}

OS and RDF \url{http://groups.google.com/group/opensocial-and-gadgets-spec/browse_thread/thread/20f62d627003509b}

OpenSocial Development Environment (OSDE, Eclipse Plugin)  \url{https://sites.google.com/site/opensocialdevenv}

\url{https://cwiki.apache.org/confluence/display/SHINDIG/Providing+your+own+data+service+implementation}

** \subsection{Socialsite}

Oracle's (former Sun's) extension to Apache Shindig. Blog \url{http://blogs.oracle.com/socialsite}

* \section{TODO}
\begin{itemize}
\item Does funambol.org has interesting implementations?
\end{itemize}
% LDAP wäre auch eine Möglichkeit für Addressdaten, aber:
% kein Standardschema, Mozilla anders als Apple
% manche Clients können evtl. Adressen aus LDAP lesen aber nicht schreiben.

% Calendaring is not easy as can be seen by the impressive list of failed projects:
% http://www.hula-project.org/ 
% Dreaming in Code - Scott Rosenberg's software epic. about the chandler failure
% http://xmpp.org/extensions/xep-0054.html

% http://en.wikibooks.org/wiki/LaTeX/Glossary

support Plain Text Format (text/plain), RFC5147 URI fragment identifier for plain text?

\begin{quote}
  Sowohl Atom als auch AtomPub definieren XML-Vokabulare, die eine Erweiterung
  mit zwei Mechanismen unterstützen. Zum einen ist im Standard definiert, dass
  neue Elemente in diesen Vokaularen selbst von standardkonformen Prozessoren
  ignoeriert werden müssen. [...] Gleichzeitig ist es überall dort, wo es nicht
  explizit verboten ist, möglich, Elemente ausanderen XML-Namespaces
  einzubetten.
\end{quote}\cite[p. 102]{Tilkov2011}


Why vCard/CardDav: many clients

Why OpenSocial / Portable Contacts:
\begin{itemize}
\item used by Google, LinkedIn,
\item used in Enterprise applications like Attlassian tools (Jira, Confluence, ...), Nuxeo CMS, ...
\item OpenSocial can be used to implement inhouse portals and populate it with data from the companies GroupWare
\end{itemize}
